#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "input_structures.glsl"
#include "raycommon.glsl"
#include "common/global.glsl"

layout(set = 0, binding = 1, rgba32f) uniform image2D image;
layout(set = 1, binding = 3) uniform accelerationStructureEXT topLevelAS;

layout(push_constant) uniform _PushConstants {
    mat4 invProj;
    mat4 invView;
    uint frame;
    uint samplesPerFrame;
};

struct ray {
    vec4 position;
    vec4 direction;
};

layout(location = 0) rayPayloadEXT HitPayload prd;

void main() 
{
    vec3 accumulatedRadiance = vec3(0.0);

    uint start = frame * samplesPerFrame;
    uint stop  = start + samplesPerFrame;

    for (uint s = start; s < stop; s++) {
        InitRNG(gl_LaunchIDEXT.x, gl_LaunchIDEXT.y, s);

        // Camera ray
        const float d1 = UniformFloat();
        const float d2 = UniformFloat();
        const vec2 jitter = vec2(d1, d2);

        const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + jitter;
        const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
        const vec2 d           = inUV * 2.0 - 1.0;

        vec4 rayOrigin    = invView * vec4(0, 0, 0, 1);
        vec4 target       = invProj * vec4(d.x, d.y, 1, 1);
        vec4 rayDirection = invView * vec4(normalize(target.xyz), 0.0);

        uint rayFlags = gl_RayFlagsOpaqueEXT;
        float tMin    = 0.001;
        float tMax    = 10000.0;

        // Integration
        vec3 radiance = vec3(0.0f);
        vec3 beta     = vec3(1.0f);
        int depth     = 0;

        while (true) {
            prd.bIsMiss   = true;
            prd.direction = -rayDirection.xyz;
            prd.s1        = UniformVec2();

            traceRayEXT(
                topLevelAS,
                gl_RayFlagsOpaqueEXT,
                0xFF,
                0,
                0,
                0,
                rayOrigin.xyz,
                0.001,
                rayDirection.xyz,
                10000.0,
                0
            );

            if (prd.bIsMiss) {
                radiance += beta * vec3(0);
                break;
            }

            // Incorporate emission
            radiance += beta * prd.emission;

            if (depth++ == 32) break;

            // PDF = 0 indicates BxDF sampling failed
            if (prd.pdf == 0) break;

            beta *= prd.f * abs(dot(prd.direction, prd.normal)) / prd.pdf;

            if (isinf(beta.x) || isnan(beta.x)) break;

            rayOrigin.xyz    = prd.position + prd.normal * 0.001;
            rayDirection.xyz = prd.direction;
        }

        accumulatedRadiance += radiance;
    }

    vec3 finalColor = accumulatedRadiance / float(samplesPerFrame);
    if (frame > 0) {
        float a = 1.0f / float(frame + 1);
        vec3 oldColor = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
        finalColor = mix(oldColor, finalColor, a);
    }
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(finalColor, 1.0));
}
