#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "input_structures.glsl"
#include "raycommon.glsl"

layout(set = 0, binding = 1, rgba32f) uniform image2D image;
layout(set = 1, binding = 3) uniform accelerationStructureEXT topLevelAS;

layout(push_constant) uniform _PushConstants {
    mat4 invProj;
    mat4 invView;
};

layout(location = 0) rayPayloadEXT HitPayload prd;

void main() 
{
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 rayOrigin = invView * vec4(0, 0, 0, 1);
    vec4 target = invProj * vec4(d.x, d.y, 1, 1);
    vec4 rayDirection = invView * vec4(normalize(target.xyz), 0.0);

    uint rayFlags = gl_RayFlagsOpaqueEXT;
    float tMin = 0.001;
    float tMax = 10000.0;

    traceRayEXT(
        topLevelAS,
        rayFlags,
        0xFF,
        0,
        0,
        0,
        rayOrigin.xyz,
        tMin,
        rayDirection.xyz,
        tMax,
        0
    );

    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(prd.hitValue, 1.0));
}
